---
- name: 'Install packages'
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: 'present'
    install_recommends: false
    update_cache: true

- name: 'Install autofs packages'
  ansible.builtin.apt:
    name: "{{ autofs_packages }}"
    state: 'present'
  when:
    - ldap_domain.autofs_searchbase is defined
    - not ldap_disable_autofs

- name: 'Place PAM config'
  ansible.builtin.copy:
    src: 'ldaphomedir'
    dest: '/usr/share/pam-configs/ldaphomedir'
    mode: '0644'
  notify: 'Reconfigure debian pam'
