---
- name: 'Install packages'
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: 'present'
    update_cache: true

- name: 'Install autofs packages'
  ansible.builtin.yum:
    name: "{{ autofs_packages }}"
    state: 'present'
  when:
    - ldap_domain.autofs_searchbase is defined
    - not ldap_disable_autofs
