---
- name: 'Include OS specific vars'
  include_vars: "{{ ansible_os_family }}.yml"
  no_log: true

- name: 'Install packages'
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: 'Configure services'
  template:
    dest: "{{ conffile.dest }}"
    src: "{{ conffile.src }}"
    mode: "{{ conffile.mode }}"
    owner: 'root'
    group: 'root'
  loop:
    - {src: 'ldap.conf.j2', mode: '0644', dest: "{{ openldap_conffile }}"}
    - {src: 'sssd.conf.j2', mode: '0600', dest: '/etc/sssd/sssd.conf'}
  loop_control:
    loop_var: 'conffile'
  notify:
    - reconfigure redhat pam
    - reconfigure debian pam
    - restart sssd
    - restart autofs
    - clear sssd cache

- name: 'Enable services - Common'
  systemd:
    name: "{{ service.name }}"
    enabled: "{{ service.enabled }}"
    masked: "{{ service.masked }}"
    state: "{{ service.state }}"
  loop:
    - {'name':'sssd', 'enabled':'yes', 'masked':'no', 'state':'started'}
    - {'name':'systemd-logind', 'enabled':'no', 'masked':'yes', 'state':'stopped'}
  loop_control:
    loop_var: 'service'

- name: 'Enable services - AutoFS'
  systemd:
    name: "{{ service.name }}"
    enabled: "{{ service.enabled }}"
    masked: "{{ service.masked }}"
    state: "{{ service.state }}"
  loop:
    - {'name':'autofs', 'enabled':'yes', 'masked':'no', 'state':'started'}
  loop_control:
    loop_var: 'service'
  when: ldap_domain.autofs_searchbase is defined

- name: 'Configure NSS'
  lineinfile:
    path: '/etc/nsswitch.conf'
    line: 'automount:      files sss'
    regexp: '^automount'
    state: 'present'
  when: ldap_domain.autofs_searchbase is defined

- name: 'Configure services - OS-specific'
  systemd:
    name: "{{ service.name }}"
    enabled: "{{ service.enabled }}"
    masked: "{{ service.masked }}"
    state: "{{ service.state }}"
  loop: "{{ os_specific_services }}"
  loop_control:
    loop_var: 'service'
  when: os_specific_services is defined

- name: 'Configure Sudo permissions for admin users'
  template:
    src: 'sudoers_10_linux_admins.j2'
    dest: '/etc/sudoers.d/10_linux_admins'
    mode: 0440
    validate: 'visudo -cf %s'
    owner: 'root'
    group: 'root'
  when: ldap_domain.linux_admins is defined
