---
- name: 'Remove packages'
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: 'absent'
    autoremove: true

- name: 'Remove autofs packages'
  ansible.builtin.yum:
    name: "{{ autofs_packages }}"
    state: 'absent'
  when:
    - ldap_domain.autofs_searchbase is defined
    - not ldap_disable_autofs
