---
- name: 'Remove packages'
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: 'absent'
    autoremove: true
  environment:
    SUDO_FORCE_REMOVE: 'yes'

- name: 'Remove autofs packages'
  ansible.builtin.apt:
    name: "{{ autofs_packages }}"
    state: 'absent'
  when:
    - ldap_domain.autofs_searchbase is defined
    - not ldap_disable_autofs

- name: 'Remove PAM config'
  ansible.builtin.file:
    path: '/usr/share/pam-configs/ldaphomedir'
    state: 'absent'
  notify: 'Reconfigure debian pam'
