---
- name: 'Include OS specific vars'
  include_vars: "{{ ansible_os_family }}.yml"
  no_log: true

- name: 'Remove packages'
  include_tasks: "remove-{{ ansible_os_family }}.yml"

- name: 'Configure services'
  file:
    path: "{{ conffile.dest }}"
    state: 'absent'
  loop:
    - {src: 'ldap.conf.j2', mode: '0644', dest: "{{ openldap_conffile }}"}
    - {src: 'sssd.conf.j2', mode: '0600', dest: '/etc/sssd/sssd.conf'}
  loop_control:
    loop_var: 'conffile'
  notify:
    - reconfigure redhat pam
    - reconfigure debian pam

- name: 'Configure NSS'
  lineinfile:
    path: '/etc/nsswitch.conf'
    line: 'automount:      files sss'
    regexp: '^automount'
    state: 'absent'
  when:
    - ldap_domain.autofs_searchbase is defined
    - not ldap_disable_autofs

- name: 'Configure Sudo permissions for admin users'
  file:
    path: '/etc/sudoers.d/10_linux_admins'
    state: 'absent'
  when: ldap_domain.linux_admins is defined
