---
- name: 'Restart sssd'
  ansible.builtin.service:
    name: 'sssd'
    state: 'restarted'

- name: 'Restart autofs'
  ansible.builtin.service:
    name: 'autofs'
    state: 'restarted'
  when: ldap_domain.autofs_searchbase is defined

- name: 'Reconfigure debian pam'
  ansible.builtin.command: '/usr/sbin/pam-auth-update --force'
  environment:
    DEBIAN_FRONTEND: 'noninteractive'
  changed_when: true
  when: ansible_facts['os_family'] == "Debian"

- name: 'Reconfigure redhat pam'
  ansible.builtin.command: "/usr/sbin/authconfig \
    --enablesssd --enablerfc2307bis \
    --enablesssdauth --disableforcelegacy \
    --enablelocauthorize --enablemkhomedir \
    --enablepamaccess --updateall"
  changed_when: true
  when: ansible_facts['os_family'] == "RedHat"

- name: 'Clear sssd cache'
  ansible.builtin.command: '/usr/sbin/sss_cache -E'
  changed_when: true
  failed_when: false
